<?php
$Template = "
<html>
<body>
<table style=\"500px\">
<tr style=\"background: #151515\">
<td style=\"height: 100px\" valign=\"middle\">
<img src=\"http://cdn.example.com/img/Home.Resource.SiteLogo.png\">
</td>
</tr>
<tr style=\"background: #EFEFEF\">
<td style=\"height: 300px\" valign=\"middle\">
[-MAILBODY_DATA-]
</td>
</tr>
<tr style=\"background: #252525\">
<td style=\"height: 30px\" valign=\"middle\">
This e-mail is intended only for members of the specified distribution group. Forwarding this message to members outside of this distribution group is strictly forbidden.
</td>
</tr>
</table>
</body>
</html>
";
?>